timezone: Europe/London
encoding: UTF-8

markdown: kramdown

permalink: /articles/:title/

gems:
  - jekyll-redirect-from

url: http://woss.name
name: Notes from a Messy Desk
description: |
  This is where I (Graeme Mathieson, often known online as
  [@mathie](https://twitter.com/mathie)) write the occasional article about
  whatever interests me this week. The latest article will always be on the
  [home page](/), but you could always peruse [previous articles](/articles/)
  too.

collections:
  categories:
    output: true
    permalink: /categories/:path/

defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: post
  -
    scope:
      path: ""
      type: draft
    values:
      layout: post

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  style: :compressed

# GitHub-enforced defaults
highlighter: pygments
lsi: false
